[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"
[[constraint]]
  name = "github.com/go-pg/pg"
  version = "7.1.6"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "2.4.5"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.25.0"
